/* The set's manifest — the ONE place a screen is declared.
 * ============================================================================
 * _chrome.js reads this once and publishes window.WF; the chart and the
 * screenshots sheet read that. A screen not in this file appears nowhere.
 *
 * The set was converted on 2026-10-04 from the prototype this repository held
 * under prototype/. Each screen is that prototype's own markup: its nav bar,
 * footer and icons were drawn by three scripts at load, and are written into
 * each file now. No screen was redrawn.
 *
 * The edges were DERIVED by scanning the real hrefs in every screen, then
 * classified by depth: home, then a list, then a dossier or a journey, then a
 * step, then the recipe. A link to a deeper screen is a step forward. Most
 * edges are the nav bar and the footer, which every screen carries.
 */
window.ROUTES = {
  product: "hamburg",
  surface: "web",

  /* Web only. The surface toggle shows `mobile` struck through. */
  surfaces: ["web"],
  /* The prototype drew one theme. */
  themes: ["light"],

  /* The laptop this is drawn against. _chrome.js publishes these as
     --frame-w / --frame-h. The two bento pages fill exactly one frame. */
  frame: { w: 1440, h: 900 },

  /* Reserved order: states · auth · onboarding · home · * · settings · store ·
     patterns. The `*` slot sorts alphabetically. There is no app — the
     repository is content and this design set — so every `route` is null. */
  flows: [

    { flow: "states", screens: [
      { file: "states/404.html", screen: "Not found", route: null, status: "review", notes: "not-found" },
    ]},
    { flow: "home", screens: [
      { file: "home/home.html", screen: "Home", route: null, status: "review", notes: "home" },
    ]},
    { flow: "grow", screens: [
      { file: "grow/tomato.html", screen: "Grow tomato", route: null, status: "review", notes: "grow-tomato" },
    ]},
    { flow: "ingredients", screens: [
      { file: "ingredients/ingredients.html", screen: "Ingredients", route: null, status: "review", notes: "ingredients" },
      { file: "ingredients/tomato.html", screen: "Tomato", route: null, status: "review", notes: "tomato" },
      { file: "ingredients/paneer.html", screen: "Paneer", route: null, status: "review", notes: "paneer" },
      { file: "ingredients/spinach.html", screen: "Spinach", route: null, status: "review", notes: "spinach" },
      { file: "ingredients/ginger.html", screen: "Ginger", route: null, status: "review", notes: "ginger" },
      { file: "ingredients/garlic.html", screen: "Garlic", route: null, status: "review", notes: "garlic" },
      { file: "ingredients/cumin.html", screen: "Cumin", route: null, status: "review", notes: "cumin" },
      { file: "ingredients/garam-masala.html", screen: "Garam masala", route: null, status: "review", notes: "garam-masala" },
    ]},
    { flow: "journeys", screens: [
      { file: "journeys/journeys.html", screen: "Journeys", route: null, status: "review", notes: "journeys" },
      { file: "journeys/milk.html", screen: "Milk journey", route: null, status: "review", notes: "milk" },
      { file: "journeys/milk-to-curd.html", screen: "Milk → Curd", route: null, status: "review", notes: "milk-to-curd" },
      { file: "journeys/milk-to-paneer.html", screen: "Milk → Paneer", route: null, status: "review", notes: "milk-to-paneer" },
      { file: "journeys/milk-to-butter.html", screen: "Milk → Butter", route: null, status: "review", notes: "milk-to-butter" },
      { file: "journeys/milk-to-ghee.html", screen: "Butter → Ghee", route: null, status: "review", notes: "milk-to-ghee" },
      { file: "journeys/milk-to-khoya.html", screen: "Milk → Khoya", route: null, status: "review", notes: "milk-to-khoya" },
      { file: "journeys/dough.html", screen: "Dough journey", route: null, status: "review", notes: "dough" },
      { file: "journeys/dough-to-chapati.html", screen: "Dough → Chapati", route: null, status: "review", notes: "dough-to-chapati" },
      { file: "journeys/dough-to-paratha.html", screen: "Dough → Paratha", route: null, status: "review", notes: "dough-to-paratha" },
      { file: "journeys/dough-to-poori.html", screen: "Dough → Poori", route: null, status: "review", notes: "dough-to-poori" },
      { file: "journeys/dough-to-pizza.html", screen: "Dough → Pizza", route: null, status: "review", notes: "dough-to-pizza" },
      { file: "journeys/dough-to-naan.html", screen: "Dough → Naan", route: null, status: "review", notes: "dough-to-naan" },
      { file: "journeys/sourdough.html", screen: "Sourdough journey", route: null, status: "review", notes: "sourdough" },
      { file: "journeys/sourdough-starter.html", screen: "Sourdough starter", route: null, status: "review", notes: "sourdough-starter" },
      { file: "journeys/sourdough-to-bread.html", screen: "Sourdough bread", route: null, status: "review", notes: "sourdough-to-bread" },
      { file: "journeys/sourdough-to-pancakes.html", screen: "Discard pancakes", route: null, status: "review", notes: "sourdough-to-pancakes" },
      { file: "journeys/sourdough-to-pizza.html", screen: "Sourdough pizza", route: null, status: "review", notes: "sourdough-to-pizza" },
      { file: "journeys/kombucha.html", screen: "Kombucha journey", route: null, status: "review", notes: "kombucha" },
      { file: "journeys/kombucha-basic.html", screen: "Base kombucha", route: null, status: "review", notes: "kombucha-basic" },
      { file: "journeys/kombucha-fruit.html", screen: "Fruit kombucha", route: null, status: "review", notes: "kombucha-fruit" },
      { file: "journeys/kombucha-ginger.html", screen: "Ginger kombucha", route: null, status: "review", notes: "kombucha-ginger" },
      { file: "journeys/kombucha-herb.html", screen: "Herb kombucha", route: null, status: "review", notes: "kombucha-herb" },
    ]},
    { flow: "pairings", screens: [
      { file: "pairings/pairings.html", screen: "Pairings", route: null, status: "review", notes: "pairings" },
    ]},
    { flow: "recipes", screens: [
      { file: "recipes/recipes.html", screen: "Recipes", route: null, status: "review", notes: "recipes" },
      { file: "recipes/palak-paneer.html", screen: "Palak paneer", route: null, status: "review", notes: "palak-paneer" },
    ]},
    { flow: "skills", screens: [
      { file: "skills/skills.html", screen: "Skills", route: null, status: "review", notes: "skills" },
    ]},
    { flow: "patterns", screens: [
      { file: "patterns/components.html", screen: "Components", route: null, status: "review", notes: "components" },
    ]},
  ],

  /* The chart. There is no splash, so it starts on the first page the site
     opens on. It ends on a recipe: the README's "tap a node, get big numbered
     steps, cook". */
  flow: {
    start: "home/home.html",
    end: ["recipes/palak-paneer.html"],
    edges: [


      /* A step forward. Rank only ever rises along these, so the graph is a DAG. */
      { from: "home/home.html", to: "ingredients/ingredients.html", label: "See all" },
      { from: "home/home.html", to: "ingredients/tomato.html", label: "Tomato 7 chapters" },
      { from: "home/home.html", to: "ingredients/paneer.html", label: "Paneer 7 chapters" },
      { from: "home/home.html", to: "ingredients/spinach.html", label: "Spinach 7 chapters" },
      { from: "home/home.html", to: "journeys/journeys.html", label: "Journeys" },
      { from: "home/home.html", to: "journeys/milk.html", label: "Milk 7 chapters" },
      { from: "home/home.html", to: "journeys/dough.html", label: "Wheat 7 chapters" },
      { from: "home/home.html", to: "journeys/sourdough.html", label: "Sourdough 7 chapters" },
      { from: "home/home.html", to: "pairings/pairings.html", label: "Pairings" },
      { from: "home/home.html", to: "recipes/recipes.html", label: "Cookbook" },
      { from: "home/home.html", to: "patterns/components.html", label: "components" },
      { from: "ingredients/ingredients.html", to: "ingredients/paneer.html", label: "Paneer" },
      { from: "ingredients/ingredients.html", to: "ingredients/spinach.html", label: "Spinach" },
      { from: "ingredients/ingredients.html", to: "ingredients/ginger.html", label: "Ginger" },
      { from: "ingredients/ingredients.html", to: "ingredients/garlic.html", label: "Garlic" },
      { from: "ingredients/ingredients.html", to: "ingredients/cumin.html", label: "Cumin spice · 1 recipe" },
      { from: "ingredients/ingredients.html", to: "ingredients/garam-masala.html", label: "Garam masala" },
      { from: "ingredients/tomato.html", to: "grow/tomato.html", label: "Full guide" },
      { from: "ingredients/paneer.html", to: "journeys/milk-to-paneer.html", label: "Milk → Paneer" },
      { from: "ingredients/paneer.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "ingredients/spinach.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "ingredients/ginger.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "ingredients/garlic.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "ingredients/cumin.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "ingredients/garam-masala.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "journeys/journeys.html", to: "journeys/milk.html", label: "Milk journey" },
      { from: "journeys/journeys.html", to: "journeys/dough.html", label: "Dough journey" },
      { from: "journeys/journeys.html", to: "journeys/sourdough.html", label: "Sourdough journey" },
      { from: "journeys/journeys.html", to: "journeys/kombucha.html", label: "Kombucha journey" },
      { from: "journeys/milk.html", to: "journeys/milk-to-curd.html", label: "Curd 6 10 hr" },
      { from: "journeys/milk.html", to: "journeys/milk-to-paneer.html", label: "Paneer 30 min · solid" },
      { from: "journeys/milk.html", to: "journeys/milk-to-butter.html", label: "Butter 20 min" },
      { from: "journeys/milk.html", to: "journeys/milk-to-ghee.html", label: "Ghee" },
      { from: "journeys/milk.html", to: "journeys/milk-to-khoya.html", label: "Khoya 2 hr" },
      { from: "journeys/milk.html", to: "recipes/palak-paneer.html", label: "Palak paneer SAVED" },
      { from: "journeys/milk-to-paneer.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "journeys/dough.html", to: "journeys/dough-to-chapati.html", label: "Dough → Chapati" },
      { from: "journeys/dough.html", to: "journeys/dough-to-paratha.html", label: "Dough → Paratha" },
      { from: "journeys/dough.html", to: "journeys/dough-to-poori.html", label: "Dough → Poori" },
      { from: "journeys/dough.html", to: "journeys/dough-to-pizza.html", label: "Dough → Pizza" },
      { from: "journeys/dough.html", to: "journeys/dough-to-naan.html", label: "Dough → Naan" },
      { from: "journeys/sourdough.html", to: "journeys/sourdough-starter.html", label: "Sourdough starter" },
      { from: "journeys/sourdough.html", to: "journeys/sourdough-to-bread.html", label: "Sourdough bread" },
      { from: "journeys/sourdough.html", to: "journeys/sourdough-to-pancakes.html", label: "Discard pancakes" },
      { from: "journeys/sourdough.html", to: "journeys/sourdough-to-pizza.html", label: "Sourdough pizza" },
      { from: "journeys/kombucha.html", to: "journeys/kombucha-basic.html", label: "Sweet tea tea + sugar" },
      { from: "journeys/kombucha.html", to: "journeys/kombucha-fruit.html", label: "Fruit kombucha" },
      { from: "journeys/kombucha.html", to: "journeys/kombucha-ginger.html", label: "Ginger kombucha" },
      { from: "journeys/kombucha.html", to: "journeys/kombucha-herb.html", label: "Herb kombucha" },
      { from: "pairings/pairings.html", to: "ingredients/tomato.html", label: "open full dossier" },
      { from: "pairings/pairings.html", to: "journeys/milk.html", label: "Milk" },
      { from: "recipes/recipes.html", to: "recipes/palak-paneer.html", label: "Palak paneer" },
      { from: "skills/skills.html", to: "journeys/milk-to-curd.html", label: "Milk → Curd" },
      { from: "skills/skills.html", to: "journeys/milk-to-paneer.html", label: "Milk → Paneer" },
      { from: "skills/skills.html", to: "journeys/milk-to-butter.html", label: "Milk → Butter" },
      { from: "skills/skills.html", to: "journeys/milk-to-ghee.html", label: "Butter → Ghee" },
      { from: "skills/skills.html", to: "journeys/milk-to-khoya.html", label: "Milk → Khoya" },

      /* Real navigation, no progress: the nav bar, the footer, a cross-link between two pages of the same depth, a recipe naming its ingredients. */
      { from: "grow/tomato.html", to: "ingredients/ingredients.html", side: true },
      { from: "grow/tomato.html", to: "pairings/pairings.html", side: true },
      { from: "grow/tomato.html", to: "recipes/recipes.html", side: true },
      { from: "grow/tomato.html", to: "patterns/components.html", side: true },
      { from: "ingredients/ingredients.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/ingredients.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/ingredients.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/ingredients.html", to: "patterns/components.html", side: true },
      { from: "ingredients/tomato.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/tomato.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/tomato.html", to: "patterns/components.html", side: true },
      { from: "ingredients/paneer.html", to: "ingredients/spinach.html", side: true },
      { from: "ingredients/paneer.html", to: "ingredients/ginger.html", side: true },
      { from: "ingredients/paneer.html", to: "ingredients/garlic.html", side: true },
      { from: "ingredients/paneer.html", to: "ingredients/cumin.html", side: true },
      { from: "ingredients/paneer.html", to: "ingredients/garam-masala.html", side: true },
      { from: "ingredients/paneer.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/paneer.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/paneer.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/paneer.html", to: "patterns/components.html", side: true },
      { from: "ingredients/spinach.html", to: "ingredients/paneer.html", side: true },
      { from: "ingredients/spinach.html", to: "ingredients/ginger.html", side: true },
      { from: "ingredients/spinach.html", to: "ingredients/garlic.html", side: true },
      { from: "ingredients/spinach.html", to: "ingredients/cumin.html", side: true },
      { from: "ingredients/spinach.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/spinach.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/spinach.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/spinach.html", to: "patterns/components.html", side: true },
      { from: "ingredients/ginger.html", to: "ingredients/spinach.html", side: true },
      { from: "ingredients/ginger.html", to: "ingredients/garlic.html", side: true },
      { from: "ingredients/ginger.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/ginger.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/ginger.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/ginger.html", to: "patterns/components.html", side: true },
      { from: "ingredients/garlic.html", to: "ingredients/ginger.html", side: true },
      { from: "ingredients/garlic.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/garlic.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/garlic.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/garlic.html", to: "patterns/components.html", side: true },
      { from: "ingredients/cumin.html", to: "ingredients/paneer.html", side: true },
      { from: "ingredients/cumin.html", to: "ingredients/spinach.html", side: true },
      { from: "ingredients/cumin.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/cumin.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/cumin.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/cumin.html", to: "patterns/components.html", side: true },
      { from: "ingredients/garam-masala.html", to: "ingredients/paneer.html", side: true },
      { from: "ingredients/garam-masala.html", to: "journeys/journeys.html", side: true },
      { from: "ingredients/garam-masala.html", to: "pairings/pairings.html", side: true },
      { from: "ingredients/garam-masala.html", to: "recipes/recipes.html", side: true },
      { from: "ingredients/garam-masala.html", to: "patterns/components.html", side: true },
      { from: "journeys/journeys.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/journeys.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/journeys.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/journeys.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk.html", to: "ingredients/paneer.html", side: true },
      { from: "journeys/milk.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk-to-curd.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk-to-curd.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/milk-to-curd.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk-to-curd.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk-to-curd.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "ingredients/paneer.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk-to-paneer.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "journeys/milk-to-ghee.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk-to-butter.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk-to-ghee.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk-to-ghee.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/milk-to-ghee.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk-to-ghee.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk-to-ghee.html", to: "patterns/components.html", side: true },
      { from: "journeys/milk-to-khoya.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/milk-to-khoya.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/milk-to-khoya.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/milk-to-khoya.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/milk-to-khoya.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "journeys/dough-to-paratha.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough-to-chapati.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough-to-paratha.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough-to-paratha.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/dough-to-paratha.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough-to-paratha.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough-to-paratha.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough-to-poori.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough-to-poori.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/dough-to-poori.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough-to-poori.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough-to-poori.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough-to-pizza.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough-to-pizza.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/dough-to-pizza.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough-to-pizza.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough-to-pizza.html", to: "patterns/components.html", side: true },
      { from: "journeys/dough-to-naan.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/dough-to-naan.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/dough-to-naan.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/dough-to-naan.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/dough-to-naan.html", to: "patterns/components.html", side: true },
      { from: "journeys/sourdough.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/sourdough.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/sourdough.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/sourdough.html", to: "patterns/components.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "journeys/sourdough-to-bread.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "journeys/sourdough-to-pancakes.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/sourdough-starter.html", to: "patterns/components.html", side: true },
      { from: "journeys/sourdough-to-bread.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/sourdough-to-bread.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/sourdough-to-bread.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/sourdough-to-bread.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/sourdough-to-bread.html", to: "patterns/components.html", side: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "patterns/components.html", side: true },
      { from: "journeys/sourdough-to-pizza.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/sourdough-to-pizza.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/sourdough-to-pizza.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/sourdough-to-pizza.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/sourdough-to-pizza.html", to: "patterns/components.html", side: true },
      { from: "journeys/kombucha.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/kombucha.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/kombucha.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/kombucha.html", to: "patterns/components.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "journeys/kombucha-fruit.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "journeys/kombucha-ginger.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "journeys/kombucha-herb.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/kombucha-basic.html", to: "patterns/components.html", side: true },
      { from: "journeys/kombucha-fruit.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/kombucha-fruit.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/kombucha-fruit.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/kombucha-fruit.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/kombucha-fruit.html", to: "patterns/components.html", side: true },
      { from: "journeys/kombucha-ginger.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/kombucha-ginger.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/kombucha-ginger.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/kombucha-ginger.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/kombucha-ginger.html", to: "patterns/components.html", side: true },
      { from: "journeys/kombucha-herb.html", to: "ingredients/ingredients.html", side: true },
      { from: "journeys/kombucha-herb.html", to: "journeys/journeys.html", side: true },
      { from: "journeys/kombucha-herb.html", to: "pairings/pairings.html", side: true },
      { from: "journeys/kombucha-herb.html", to: "recipes/recipes.html", side: true },
      { from: "journeys/kombucha-herb.html", to: "patterns/components.html", side: true },
      { from: "pairings/pairings.html", to: "ingredients/ingredients.html", side: true },
      { from: "pairings/pairings.html", to: "journeys/journeys.html", side: true },
      { from: "pairings/pairings.html", to: "recipes/recipes.html", side: true },
      { from: "pairings/pairings.html", to: "patterns/components.html", side: true },
      { from: "recipes/recipes.html", to: "ingredients/ingredients.html", side: true },
      { from: "recipes/recipes.html", to: "journeys/journeys.html", side: true },
      { from: "recipes/recipes.html", to: "pairings/pairings.html", side: true },
      { from: "recipes/recipes.html", to: "patterns/components.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/ingredients.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/paneer.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/spinach.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/ginger.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/garlic.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/cumin.html", side: true },
      { from: "recipes/palak-paneer.html", to: "ingredients/garam-masala.html", side: true },
      { from: "recipes/palak-paneer.html", to: "journeys/journeys.html", side: true },
      { from: "recipes/palak-paneer.html", to: "journeys/milk.html", side: true },
      { from: "recipes/palak-paneer.html", to: "journeys/milk-to-paneer.html", side: true },
      { from: "recipes/palak-paneer.html", to: "pairings/pairings.html", side: true },
      { from: "recipes/palak-paneer.html", to: "patterns/components.html", side: true },
      { from: "skills/skills.html", to: "ingredients/ingredients.html", side: true },
      { from: "skills/skills.html", to: "journeys/journeys.html", side: true },
      { from: "skills/skills.html", to: "pairings/pairings.html", side: true },
      { from: "skills/skills.html", to: "recipes/recipes.html", side: true },
      { from: "skills/skills.html", to: "patterns/components.html", side: true },
      { from: "patterns/components.html", to: "ingredients/ingredients.html", side: true },
      { from: "patterns/components.html", to: "journeys/journeys.html", side: true },
      { from: "patterns/components.html", to: "pairings/pairings.html", side: true },
      { from: "patterns/components.html", to: "recipes/recipes.html", side: true },

      /* A return: a breadcrumb, a "←" button, the logo, and every way out of the 404. */
      { from: "states/404.html", to: "home/home.html", back: true },
      { from: "states/404.html", to: "ingredients/ingredients.html", back: true },
      { from: "states/404.html", to: "journeys/journeys.html", back: true },
      { from: "states/404.html", to: "pairings/pairings.html", back: true },
      { from: "states/404.html", to: "recipes/recipes.html", back: true },
      { from: "states/404.html", to: "patterns/components.html", back: true },
      { from: "grow/tomato.html", to: "home/home.html", back: true },
      { from: "grow/tomato.html", to: "ingredients/tomato.html", back: true },
      { from: "ingredients/ingredients.html", to: "home/home.html", back: true },
      { from: "ingredients/tomato.html", to: "home/home.html", back: true },
      { from: "ingredients/tomato.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/paneer.html", to: "home/home.html", back: true },
      { from: "ingredients/paneer.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/spinach.html", to: "home/home.html", back: true },
      { from: "ingredients/spinach.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/ginger.html", to: "home/home.html", back: true },
      { from: "ingredients/ginger.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/garlic.html", to: "home/home.html", back: true },
      { from: "ingredients/garlic.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/cumin.html", to: "home/home.html", back: true },
      { from: "ingredients/cumin.html", to: "ingredients/ingredients.html", back: true },
      { from: "ingredients/garam-masala.html", to: "home/home.html", back: true },
      { from: "ingredients/garam-masala.html", to: "ingredients/ingredients.html", back: true },
      { from: "journeys/journeys.html", to: "home/home.html", back: true },
      { from: "journeys/milk.html", to: "home/home.html", back: true },
      { from: "journeys/milk.html", to: "journeys/journeys.html", back: true },
      { from: "journeys/milk-to-curd.html", to: "home/home.html", back: true },
      { from: "journeys/milk-to-curd.html", to: "journeys/milk.html", back: true },
      { from: "journeys/milk-to-paneer.html", to: "home/home.html", back: true },
      { from: "journeys/milk-to-paneer.html", to: "journeys/milk.html", back: true },
      { from: "journeys/milk-to-butter.html", to: "home/home.html", back: true },
      { from: "journeys/milk-to-butter.html", to: "journeys/milk.html", back: true },
      { from: "journeys/milk-to-ghee.html", to: "home/home.html", back: true },
      { from: "journeys/milk-to-ghee.html", to: "journeys/milk.html", back: true },
      { from: "journeys/milk-to-khoya.html", to: "home/home.html", back: true },
      { from: "journeys/milk-to-khoya.html", to: "journeys/milk.html", back: true },
      { from: "journeys/dough.html", to: "home/home.html", back: true },
      { from: "journeys/dough.html", to: "journeys/journeys.html", back: true },
      { from: "journeys/dough-to-chapati.html", to: "home/home.html", back: true },
      { from: "journeys/dough-to-chapati.html", to: "journeys/dough.html", back: true },
      { from: "journeys/dough-to-paratha.html", to: "home/home.html", back: true },
      { from: "journeys/dough-to-paratha.html", to: "journeys/dough.html", back: true },
      { from: "journeys/dough-to-poori.html", to: "home/home.html", back: true },
      { from: "journeys/dough-to-poori.html", to: "journeys/dough.html", back: true },
      { from: "journeys/dough-to-pizza.html", to: "home/home.html", back: true },
      { from: "journeys/dough-to-pizza.html", to: "journeys/dough.html", back: true },
      { from: "journeys/dough-to-naan.html", to: "home/home.html", back: true },
      { from: "journeys/dough-to-naan.html", to: "journeys/dough.html", back: true },
      { from: "journeys/sourdough.html", to: "home/home.html", back: true },
      { from: "journeys/sourdough.html", to: "journeys/journeys.html", back: true },
      { from: "journeys/sourdough-starter.html", to: "home/home.html", back: true },
      { from: "journeys/sourdough-starter.html", to: "journeys/sourdough.html", back: true },
      { from: "journeys/sourdough-to-bread.html", to: "home/home.html", back: true },
      { from: "journeys/sourdough-to-bread.html", to: "journeys/sourdough.html", back: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "home/home.html", back: true },
      { from: "journeys/sourdough-to-pancakes.html", to: "journeys/sourdough.html", back: true },
      { from: "journeys/sourdough-to-pizza.html", to: "home/home.html", back: true },
      { from: "journeys/sourdough-to-pizza.html", to: "journeys/sourdough.html", back: true },
      { from: "journeys/kombucha.html", to: "home/home.html", back: true },
      { from: "journeys/kombucha.html", to: "journeys/journeys.html", back: true },
      { from: "journeys/kombucha-basic.html", to: "home/home.html", back: true },
      { from: "journeys/kombucha-basic.html", to: "journeys/kombucha.html", back: true },
      { from: "journeys/kombucha-fruit.html", to: "home/home.html", back: true },
      { from: "journeys/kombucha-fruit.html", to: "journeys/kombucha.html", back: true },
      { from: "journeys/kombucha-ginger.html", to: "home/home.html", back: true },
      { from: "journeys/kombucha-ginger.html", to: "journeys/kombucha.html", back: true },
      { from: "journeys/kombucha-herb.html", to: "home/home.html", back: true },
      { from: "journeys/kombucha-herb.html", to: "journeys/kombucha.html", back: true },
      { from: "pairings/pairings.html", to: "home/home.html", back: true },
      { from: "recipes/recipes.html", to: "home/home.html", back: true },
      { from: "recipes/palak-paneer.html", to: "home/home.html", back: true },
      { from: "recipes/palak-paneer.html", to: "recipes/recipes.html", back: true },
      { from: "skills/skills.html", to: "home/home.html", back: true },
      { from: "patterns/components.html", to: "home/home.html", back: true },
    ],
  },

  updated: "2026-10-04",

  /* What the product has, or says it has, and no screen draws. */
  missing: [
    { what: "Search", why: "home and Journeys draw a search field, and Pairings a picker. Nothing answers them: the set has no script" },
    { what: "Filters", why: "the chips on Ingredients, Journeys and Recipes are buttons that filter nothing" },
    { what: "skills/skills.html has no way in", why: "the nav dropped Skills on 2026-07-19 and no screen links to it. It is drawn, declared, and unreachable" },
    { what: "Seven season tiles on Home go nowhere", why: "Mango, Sweet corn, Berries, Cucumber, Peppers, Basil and Stone fruit have no dossier. Their links are #" },
    { what: "Dossiers for Milk, Wheat and Sourdough", why: "Home shows them as ingredients with 7 chapters; the tiles open their journeys instead. See features/0001" },
    { what: "Six dossiers are the older chapter layout", why: "only Tomato was redrawn as a single-frame bento. See features/0002" },
    { what: "The narrow layout", why: "the stylesheet has rules for 900, 640 and 560px and the README calls the site mobile-first. No screen is drawn at that width, and there is no mobile surface" },
    { what: "A dark theme", why: "the prototype drew none" },
    { what: "Flour, Base dough and the wild-yeast node", why: "three nodes in the Dough and Sourdough graphs, and two notes on Milk → Paneer, link to #" },
  ],

  states: {
    empty:   { drawn: null, note: "no list is drawn empty. Recipes holds one recipe and says so" },
    loading: { drawn: null, note: "static pages. Nothing loads after the page does" },
    error:   { drawn: null, note: "app-wide only: states/404.html" },
    offline: { drawn: null, note: "a static site. Nothing works offline and nothing claims to" },
    locked:  { drawn: null, note: "nothing is gated. There are no accounts and nothing is sold" },
  },
};
